if (WIN32)
    # Visual Studio 打开 sln 文件 和 直接打开 cmake 文件夹 调试时有差异。
    # sln 执行路径是生成路径    cmake 目录是 生成路径/类型
    # 复制的依赖资源要多复制一份。
    file(
        COPY ${ELEMENTS_RESOURCES} ${ELEMENTS_APP_RESOURCES}
        DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CONFIGURATION_TYPES}/resources"
    )

    message(STATUS "${CAIRO_DLL}, ${FREETYPE_DLL}, ${FONTCONFIG_DLL}, ${ICONV_DLL}, ${XML2}  => ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CONFIGURATION_TYPES}")

    file(COPY ${CAIRO_DLL} DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CONFIGURATION_TYPES}")
    file(COPY ${FREETYPE_DLL} DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CONFIGURATION_TYPES}")
    file(COPY ${FONTCONFIG_DLL} DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CONFIGURATION_TYPES}")
    file(COPY ${ICONV_DLL} DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CONFIGURATION_TYPES}")
    file(COPY ${XML2} DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CONFIGURATION_TYPES}")
endif()